services:
  db:
    image: postgres:16-alpine
    container_name: fintrack-db
    environment:
      POSTGRES_USER: Admin
      POSTGRES_PASSWORD: nimda
      POSTGRES_DB: fintrack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fintrack-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fintrack.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: